version: "3.7"
services:
    hive:
        build: .
        image: hive/condenser:latest
        container_name: hive
        expose:
          - "8080"
        environment:
            VIRTUAL_HOST: hivean.com
            VIRTUAL_PORT: 8080
            SDC_CLIENT_STEEMD_URL: https://anyx.io
            SDC_SERVER_STEEMD_URL: https://anyx.io
            SDC_DISABLE_SIGNUPS: 1
            SDC_SITE_DOMAIN: hivean.com
            SDC_IMAGE_PROXY_PREFIX: https://images.hive.blog/
            SDC_UPLOAD_IMAGE_URL: https://images.hive.blog
            SDC_ALT_API_ENDPOINTS: "https://api.hive.blog https://anyx.io https://api.openhive.network https://api.hivekings.com"
            SDC_HELMET_CONNECTSRC: "'self' https://hivean.com https://images.hive.blog https://anyx.io https://api.hive.blog https://api.openhive.network https://api.hivekings.com https://hivebuzz.me https://peakd.com https://hivesigner.com https://gist.github.com"
            SDC_HELMET_STYLESRC: "'self' 'unsafe-inline' fonts.googleapis.com platform.twitter.com embed.redditmedia.com github.githubassets.com"
            ESTEEM_ELASTIC_SEARCH_API_KEY: "169EALKZ7LENMA1S5EBT55DGQCWX8JE6YCJRNR05TVCFJYUICRFEXRMY8YSS"
            WALLET_URL: https://wallet.hivean.com
        networks:
            - proxy_reverse-proxy
        restart: always

networks:
    proxy_reverse-proxy:
        external:
            name: proxy_reverse-proxy
